In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('/kaggle/input/multi-feature-linear-data/train.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
import math
median_val = math.floor(df.bedrooms.median())
median_val

4

In [6]:
df.bedrooms = df.bedrooms.fillna(median_val)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
model = linear_model.LinearRegression()
model.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [8]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [9]:
model.intercept_

221323.00186540384

In [11]:
model.predict([[3000,3,15]])

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([579201.19929613])

In [13]:
ex = pd.read_csv('/kaggle/input/multi-feature-linear-data/example.csv')
ex

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [15]:
ex.experience = ex.experience.fillna('zero')

In [16]:
!pip install word2number

  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5582 sha256=a5d68a8f41ebc316e6335e7b0e901d899670104f3499a40f7b2ecb4435bffeb4
  Stored in directory: /root/.cache/pip/wheels/0e/e1/0b/575d02bdf2c7ff9c9be5490db69e8d4e2e26b5523e295137eb
Successfully built word2number


In [17]:
from word2number import w2n

In [23]:
ex.experience = ex.experience.apply(w2n.word_to_num)    

In [39]:
med = math.floor(ex['test_score(out of 10)'].mean())

In [40]:
ex['test_score(out of 10)'] = ex['test_score(out of 10)'].fillna(med)

In [41]:
ex

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

# Now Train the model

In [42]:
mod = linear_model.LinearRegression()
mod.fit(ex[['experience','test_score(out of 10)','interview_score(out of 10)']], ex['salary($)'])

LinearRegression()

In [43]:
mod.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [44]:
mod.intercept_

17737.263464337717

In [45]:
mod.predict([[2,9,6]])

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([53205.96797671])

In [46]:
mod.predict([[12,10,10]])

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([92002.18340611])